id: P410A6499
initial_creation_type: input
source_metadata:
  title: Gorampa Sönam Senge
  parent: 2. Collected works
  source: https://sakyalibrary.com
  bases:
    c081:
      title: ༼ཀ༽ཕྱོགས་ཐམས་ཅད་ལས་རྣམ་པར་རྒྱལ་བ་ཀུན་མཁྱེན་བླ་མ་ཆེན་པོའི་གསུང་འབུམ།་་་་་དབུ་ཤོག་ཀུན་མཁྱེན་བླ་མར་མཆོད་བརྗོད་ཞལ་གསུངས་མ།
        ཀུན་མཁྱེན་བླ་མའི་གསུང་འབུམ་གྱི་མཚན་གྲངས་དང་བཞུགས་བྱང་མདོར་བསྡུས་སུ་བཀོད་པ།
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: c081.txt
      order: 1
    f67b:
      title: ༼ཀ༽རྗེ་བླ་མ་ཀུན་མཁྱེན་ཆེན་པོའི་བཀའ་འབུམ་གྱི་པོ་ཏི་ཐོག་མའི་སྐབས་ལས་བསྟོད་ཚོགས་ཀྱི་སྐོར་སོགས།
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: f67b.txt
      order: 2
    57fc:
      title: ༼ཀ༽ཕར་ཕྱིན་དང་ཚད་མ་བརྒྱུད་པའི་བླ་མ་ལ་མཆོད་བསྟོད་རིན་པོ་ཆེའི་ཕྲེང་བ་ཞེས་བྱ་བ་བཞུགས།
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: 57fc.txt
      order: 3
    a91f:
      title: ༼ཀ༽རྟགས་འཇུག་གི་ཊཱིཀ་བཞུགས།
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: a91f.txt
      order: 4
    b94d:
      title: ༼ཀ༽རྒྱས་པའི་བསྟན་བཅོས་ཚད་མ་རྣམ་འགྲེལ་གྱི་རྣམ་པར་བཤད་པ་ཀུན་ཏུ་བཟང་པོའི་འོད་ཟེར་བཞུགས།
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: b94d.txt
      order: 5
    2de9:
      title: ༼ཀ༽ཚད་མ་གྲུབ་པའི་ལེའུ་བཞུགས།
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: 2de9.txt
      order: 6
    e5e4:
      title: ༼ཀ༽མངོན་སུམ་ལེའུ་བཞུགས།
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: e5e4.txt
      order: 7
    19a9:
      title: ༼ཀ༽གཞན་དོན་ལེའུ་བཞུགས།
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: 19a9.txt
      order: 8
    29dd:
      title: ༼ཁ༽རྒྱས་པའི་བསྟན་བཅོས་ཚད་མ་རྣམ་འགྲེལ་གྱི་ངག་དོན་ཀུན་ཏུ་བཟང་པོའི་ཉི་མ།
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: 29dd.txt
      order: 9
    fba4:
      title: ༼ཁ༽སྡེ་བདུན་མདོ་དང་བཅས་པའི་དགོངས་པ་ཕྱིན་ཅི་མ་ལོག་པར་འགྲེལ་པ་ཚད་མ་རིགས་པའི་གཏེར་གྱི་དོན་གསལ་བར་བྱེད་པ།
        རྟགས་ཀྱི་འཁོར་ལོ་གཏན་ལ་དབབ་པ་ལ།
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: fba4.txt
      order: 10
    7a40:
      title: ༼ག༽ཚད་མ་རིགས་པའི་གཏེར་གྱི་དཀའ་བའི་གནས་རྣམ་པར་བཤད་པ་སྡེ་བདུན་རབ་གསལ།
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: 7a40.txt
      order: 11
    23e3:
      title: ༼ང་༽རབ་ཏུ་བྱུང་བ་རྣམས་ཀྱི་བསླབ་བྱ་ཉམས་སུ་བླང་བའི་ཆོས་འདུལ་བ་རྒྱ་མཚོའི་སྙིང་པོ།
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: 23e3.txt
      order: 12
    b01e:
      title: ༼ང་༽ཆོས་མངོན་པ་མཛོད་ཀྱི་བཤད་ཐབས་ཀྱི་མན་ངག་ངོ་མཚར་གསུམ་ལྡན།་་་་་བརྩམས་འཕྲོ་ཅན།
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: b01e.txt
      order: 13
    8d92:
      title: ༼ང་༽ཕུང་ཁམས་སྐྱེ་མཆེད་ཀྱི་རྣམ་གཞག་ཇི་སྙེད་ཤེས་བྱའི་སྒོ་འབྱེད།
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: 8d92.txt
      order: 14
    9e45:
      title: ༼ང་༽དབུ་མ་རྩ་བའི་ཤེས་རབ་ཀྱི་རྣམ་པར་བཤད་པ་ཡང་དག་ལྟ་བའི་འོད་ཟེར།
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: 9e45.txt
      order: 15
    9e46:
      title: ༼ཅ༽རྒྱལ་བ་ཐམས་ཅད་ཀྱི་ཐུགས་ཀྱི་དགོངས་པ་ཟབ་མོ་དབུ་མའི་དེ་ཁོ་ན་ཉིད་སྤྱིའི་ངག་གིས་སྟོན་པ་ངེས་དོན་རབ་གསལ།
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: 9e46.txt
      order: 16
    4c7b:
      title: ༼ཅ༽ལྟ་བའི་ཤན་འབྱེད་ཐེག་མཆོག་གནད་ཀྱི་ཟླ་ཟེར།
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: 4c7b.txt
      order: 17
    5d0f:
      title: ༼ཅ༽དབུ་མ་ལ་འཇུག་པའི་དཀྱུས་ཀྱི་ས་བཅད་པ་དང་གཞུང་སོ་སོའི་དཀའ་བའི་གནས་ལ་དཔྱད་པ་ལྟ་བ་ངན་སེལ།
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: 5d0f.txt
      order: 18
    fae6:
      title: ༼ཆ༽ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པའི་མན་ངག་གི་བསྟན་བཅོས་མངོན་པར་རྟོགས་པའི་རྒྱན་འགྲེལ་པ་དང་བཅས་པའི་དཀའ་བའི་གནས་རྣམ་པར་བཤད་པ་ཡུམ་དོན་རབ་གསལ།
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: fae6.txt
      order: 19
    9a66:
      title: ༼ཇ༽ ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པའི་མན་ངག་གི་བསྟན་བཅོས་མངོན་རྟོགས་རྒྱན་གྱི་གཞུང་སྔ་ཕྱིའི་འབྲེལ་དང་དཀའ་གནས་ལ་དཔྱད་པ་སྦས་དོན་ཟབ་མོའི་གཏེར་གྱི་ཁ་འབྱེད།
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: 9a66.txt
      order: 20
    8e93:
      title: ༼ཇ༽འགྲེལ་པ་དོན་གསལ་གྱི་ངག་དོན།
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: 8e93.txt
      order: 21
    3f19:
      title: ༼ཉ༽ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པའི་མན་ངག་གི་བསྟན་བཅོས་མངོན་པར་རྟོགས་པའི་རྒྱན་གྱི་མཚོན་བྱེད་ཀྱི་ཆོས་རྣམས་ཀྱི་ཡན་ལག་རྒྱས་པར་བཤད་པ་སྦས་དོན་རབ་གསལ་ལ།
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: 3f19.txt
      order: 22
    684c:
      title: ༼ཉ༽ཞུགས་གནས་ཀྱི་རྣམ་གཞག་སྐྱེས་བུ་མཆོག་གི་གསལ་བྱེད་ལ།
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: 684c.txt
      order: 23
    8baf:
      title: ༼ཉ༽མཐར་གྱིས་གནས་པའི་སྙོམས་པར་འཇུག་པའི་རྣམ་བཤད་སྙོམས་འཇུག་རབ་གསལ་ལ།
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: 8baf.txt
      order: 24
    bd75:
      title: ༼ཉ༽རྟེན་འབྲེལ་གྱི་རྣམ་པར་བཞག་པ་འཁོར་འདས་རབ་གསལ་ལ།
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: bd75.txt
      order: 25
    5dd6:
      title: ༼ཉ༽བློ་སྦྱོང་ཞེན་པ་བཞི་བྲལ་གྱི་ཁྲིད་ཡིག་ཟབ་དོན་གནད་ཀྱི་ལྡེའུ་མིག
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: 5dd6.txt
      order: 26
    001d:
      title: ༼ཏ༽སྡོམ་པ་གསུམ་གྱི་རབ་ཏུ་དབྱེ་བའི་རྣམ་བཤད་རྒྱལ་བའི་གསུང་རབ་ཀྱི་དགོངས་པ་གསལ་བ།
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: 001d.txt
      order: 27
    7f0e:
      title: ༼ཏ༽སྡོམ་གསུམ་རབ་དབྱེའི་སྤྱི་དོན་ཡིད་བཞིན་ནོར་བུ།
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: 7f0e.txt
      order: 28
    cbe8:
      title: ༼ཏ༽སྡོམ་གསུམ་གྱི་བསྟན་བཅོས་ལ་དྲིས་ཤིང་རྩོད་པའི་ལན་སྡོམ་གསུམ་འཁྲུལ་སྤོང་།
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: cbe8.txt
      order: 29
    bfde:
      title: ༼ཏ༽མདོ་རྒྱུད་ཀུན་གྱི་དོན་བསྡུས་པ་སྙིང་པོ་ཡིད་ཀྱི་མུན་པ་རྣམ་པར་སེལ་བ།
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: bfde.txt
      order: 30
    280f:
      title: ༼ཏ༽སྡོམ་པ་གསུམ་གྱི་རབ་ཏུ་དབྱེ་བའི་ཁ་སྐོང་གཞི་ལམ་འབྲས་གསུམ་གསལ་བར་བྱེད་པའི་ལེགས་བཤད་འོད་ཀྱི་སྣང་བ།
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: 280f.txt
      order: 31
    bacc:
      title: ༼ཏ༽སྡོམ་གསུམ་ཁ་སྐོང་གི་བསྡུས་དོན།
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: bacc.txt
      order: 32
    573b:
      title: ༼ཐ༽རྗེ་བཙུན་བླ་མ་མུས་པ་ཆེན་པོའི་རྣམ་པར་ཐར་པ་ངོ་མཚར་རྒྱ་མཚོ།
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: 573b.txt
      order: 33
    1c1d:
      title: ༼ཐ༽དྲིས་ལན་པད་མོ་བཞད་པ། ཉི་ཟླ་སེང་གེའི་དྲིས་ལན། མདོ་ཁམས་པ་དབང་ཕྱུག་རྒྱལ་མཚན་གྱིས་དྲིས་ལན།
        སྔགས་འཆང་རཏྣ་ཤྲཱིའི་དྲིས་ལན། རིན་ཆེན་དཔལ་གྱི་དྲིས་ལན། མུས་སྲད་པ་རྡོ་རྗེ་རྒྱལ་མཚན་གྱི་དྲིས་ལན།
        སྒྲུབ་པ་ཁྲིམས་བཟང་པོའི་དྲིས་ལན། ལྡན་མ་ཤེས་རབ་སེང་གེའི་དྲིས་ལན། བཀའ་བཅུ་པ་རིན་ཆེན་བྱང་ཆུབ་ཀྱི་དྲིས་ལན་ཟླ་ཟེར་བྱ་བ།
        ལྡན་མ་ཚེ་རྒྱལ་སྐྱབས་ཀྱི་དྲིས་ལན་བཅས་བཞུགས།
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: 1c1d.txt
      order: 34
    bdf2:
      title: ༼ཐ༽རྣལ་འབྱོར་ཆེན་པོའི་སྡོམ་པའི་གནད་བྱེ་བྲག་ཏུ་བཤད་པ་ཟབ་དོན་བདུད་རྩིའི་ཉིང་ཁུ་འཆི་བ་མེད་པའི་གོ་འཕང་སྦྱིན་པ་ལ།
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: bdf2.txt
      order: 35
    bc07:
      title: ༼ཐ༽ཟབ་དོན་བདུད་རྩིའི་ཉིང་ཁུ་འཆི་བ་མེད་པའི་གོ་འཕང་སྦྱིན་པའི་རྣམ་བཤད་བདུད་རྩི་སྤེལ་བ།
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: bc07.txt
      order: 36
    7eb6:
      title: ༼ཐ༽འཇིག་རྟེན་དབང་ཕྱུག་གི་གཞུང་བཞི་ཉམས་སུ་ལེན་ཚུལ།
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: 7eb6.txt
      order: 37
    eb69:
      title: ༼ཐ༽ཡང་དག་པར་རྫོགས་པའི་སངས་རྒྱས་གཟི་བརྗིད་ཀྱི་རྒྱལ་པོའི་བརྟག་པའི་རྣམ་པར་བཤད་པ་གཞན་ཕན་ཀུན་ཁྱབ།
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: eb69.txt
      order: 38
    8f06:
      title: ༼ཐ༽ཀུན་རིག་གི་ཞི་བའི་སྦྱིན་སྲེག
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: 8f06.txt
      order: 39
    fab2:
      title: ༼ཐ༽བཅོམ་ལྡན་འདས་ཀུན་རིག་གི་ཆོ་ག་ལག་ཏུ་བླང་བའི་རིམ་པ་གཞན་ཕན་འོད་ཟེར་ལ་རྩོད་པ་སྤོང་བ་གཞན་ཕན་གནོད་འཇོམས།
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: fab2.txt
      order: 40
    330b:
      title: ༼ཐ༽འཇམ་པའི་རྡོ་རྗེའི་སྒྲུབ་ཐབས་ཀུན་ཏུ་བཟང་པོའི་ཉི་འོད།
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: 330b.txt
      order: 41
    9bde:
      title: ༼ཐ༽འཇམ་པའི་རྡོ་རྗེའི་དཀྱིལ་ཆོག་ཡེ་ཤེས་རྣམ་རོལ་ལ། འཇམ་པའི་རྡོ་རྗེ་དང་སྤྱན་རས་གཟིགས་ཀྱི་སྒྲུབ་དཀྱིལ་མི་འདྲ་བའི་ཁྱད་པར།
        འཇམ་པའི་རྡོ་རྗེའི་གཏོར་ཆོག་ཕྲིན་ལས་རྣམ་རོལ།
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: 9bde.txt
      order: 42
    a193:
      title: ༼ཐ༽དཔལ་གསང་བ་འདུས་པ་འཇམ་པའི་རྡོ་རྗེའི་ཕྱི་རོལ་ཚོགས་བསག་གི་ཆོ་ག་མཎྜལ་ལ་བརྟེན་ཏེ་སྒྲུབ་ཅིང་མཆོད་པ།
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: a193.txt
      order: 43
    f932:
      title: ༼ཐ༽གསང་བ་འདུས་པའི་རིམ་པ་ལྔའི་མན་ངག་གི་ཁྲིད་ཡིག་ཟུང་འཇུག་གསལ་བའི་སྒྲོན་མེ།
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: f932.txt
      order: 44
    f985:
      title: ༼ཐ༽རྡོ་རྗེ་ཐེག་པ་ལ་ལོག་སྨྲ་ཚར་གཅོད་པ་རིགས་པའི་མཚོན་ཆ།
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: f985.txt
      order: 45
    ade3:
      title: ༼ད༽དཔལ་གསང་བ་འདུས་པའི་སྒྲུབ་ཐབས་ཀུན་ཏུ་བཟང་པོའི་ཉི་འོད་ཀྱི་དོན་འགྲེལ་ལམ་བཟང་གསལ་བའི་སྣང་བ།
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: ade3.txt
      order: 46
    82eb:
      title: ༼ད༽དཔལ་རྡོ་རྗེ་འཇིགས་བྱེད་ཀྱི་སྒྲུབ་ཐབས། སྤྲོས་མེད་རྒྱུན་གྱི་རྣལ་འབྱོར།
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: 82eb.txt
      order: 47
    433e:
      title: ༼ད༽དཔལ་རྡོ་རྗེ་འཇིགས་བྱེད་ཀྱི་དཀྱིལ་འཁོར་གྱི་ཆོ་ག
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: 433e.txt
      order: 48
    84c2:
      title: ༼ད༽བདེ་མཆོག་ཆོས་འབྱུང་བརྒྱུད་པའི་རྣམ་ཐར་དང་བཅས་པ།
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: 84c2.txt
      order: 49
    9d1e:
      title: ༼ད༽དཔལ་འཁོར་ལོ་བདེ་མཆོག་ལཱུ་ནག་གཉིས་ཀྱི་སྒྲུབ་ཐབས་མངལ་སྒོང་སྦྱོང་བའི་ཚུལ།
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: 9d1e.txt
      order: 50
    eb68:
      title: ༼ད༽མཁའ་སྤྱོད་སྒོ་འབྱེད་ཅེས་བྱ་བ།
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: eb68.txt
      order: 51
    66be:
      title: ༼ད༽དཔལ་འཁོར་ལོ་བདེ་མཆོག་ལཱུ་ཧི་པའི་རྣམ་བཤད་དཔག་བསམ་ལྗོན་པ།
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: 66be.txt
      order: 52
    9d0e:
      title: ༼ན༽གསུང་ངག་ལམ་འབྲས་དོན་བསྡུས་མའི་རྣམ་བཤད་ཟབ་དོན་གནད་ཀྱི་སྒྲོན་མེ།
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: 9d0e.txt
      order: 53
    a518:
      title: ༼ན༽ལམ་འབྲས་བུ་དང་བཅས་པའི་མན་ངག་གི་བྱུང་ཚུལ་གསུང་ངག་བསྟན་པ་རྒྱས་པའི་ཉི་འོད་ཁ་སྐོང་དང་བཅས་པ།
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: a518.txt
      order: 54
    a20e:
      title: ༼ན༽དཔལ་ཀྱཻ་རྡོ་རྗེའི་མངོན་པར་རྟོགས་པ་མན་ངག་གི་སྣང་བ།
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: a20e.txt
      order: 55
    8ed8:
      title: ༼ན༽ཀྱཻ་རྡོ་རྗེ་མན་ངག་ལུགས་ཀྱི་མཆོད་གཏོར་གྱི་རྣལ་འབྱོར། མཚོ་སྐྱེས་ལུགས་ཀྱི་ཕྲ་མིག
        སམྦུ་ཊའི་ཆོ་གའི་གསལ་བྱེད། དབང་ཆུ་ཆེན་མོའི་ཆོ་གའི་གསལ་བྱེད། རྟེན་རྙིང་པ་ལ་བྱ་བའི་ཨརྒྷའི་ཆོ་ག
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: 8ed8.txt
      order: 56
    b0e3:
      title: ༼ན༽རྗེ་བཙུན་རྡོ་རྗེ་བདག་མེད་མའི་མངོན་དཀྱིལ་གྱི་ཐོ་ཡིག
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: b0e3.txt
      order: 57
    6c9a:
      title: ༼ན༽གུར་རིགས་བསྡུས་པའི་སྒྲུབ་ཐབས་དངོས་གྲུབ་རྒྱ་མཚོ། རྡོ་རྗེ་གུར་གྱི་དཀྱིལ་ཆོག་བདེ་ཆེན་རྒྱ་མཚོ།
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: 6c9a.txt
      order: 58
    d007:
      title: ༼ན༽རབ་གནས་ཆོ་ག་དགེ་ལེགས་རྒྱ་མཚོ།
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: d007.txt
      order: 59
    f813:
      title: ༼ན༽མགོན་པོའི་སྲུང་འཁོར།
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: f813.txt
      order: 60
    299a:
      title: ༼ན༽ལམ་དུས་ཀྱི་དབང་བསྐུར་བ་དང་། གསོ་བ་དང་། བིར་སྲུང་ཐུན་མོང་མ་ཡིན་པའི་ཕྱག་ལེན།
        འདིའི་ནང་ལེའུ་ཚན་ལྔ་སྟེ། ལམ་དུས་ཀྱི་དབང་བསྐུར་བ། ལམ་དུས་ཀྱི་དབང་གསོ་བའི་ཕྱག་ལེན།
        རྣལ་འབྱོར་དབང་ཕྱུང་གི་སྲུང་བ་ཐུན་མོང་མ་ཡིན་པའི་བྱིན་རླབས་ཀྱི་ཚུལ། རྣམ་འཇོམས་བིར་ལུགས་ཀྱི་བྱིན་རླབས།
        ག་ཡ་དྷ་ར་ནས་བརྒྱུད་པའི་མགོན་པོ་དཔའ་གཅིག་གི་རྗེས་གནང་བྱ་ཚུལ།
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: 299a.txt
      order: 61
    b80d:
      title: ༼ན༽ལམ་འབྲས་བླ་མ་བརྒྱུད་པ་ལ་ཡན་ལག་བདུན་པ་འབུལ་ཞིང་གསོལ་བ་གདབ་པ། བརྡ་དགྲོལ་ངེས་པའི་དཔལ་སྟེར།
        རྒྱུད་ཀྱི་ཚིག་དོན་ལ་དོགས་གཅོད། སཾ་བུ་ཊའི་བསྡུས་དོན་ཚིགས་བཅད་མ། གཞུང་ཇི་ལྟ་བ་བཞིན་དུ་བཀྲི་བའི་ལམ་སྤྱིའི་རྣམ་གཞག
        མངོན་པར་བྱང་ཆུབ་པའི་ཚུལ་ལ་ངེས་ཕྱེ་བ། གཞལ་ཡས་ཁང་གི་ཆག་ཆད། ཀུན་རིག་རིགས་བསྡུས་བདེ་མཆོག་གསང་འདུས་སོགས་ཀྱི་བློས་སློང་གི་སྦྲག་སོགས་ཀྱི་ཁྱད་པར།
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: b80d.txt
      order: 62
    823d:
      title: ༼ན༽སྣང་བ་གསུམ་གྱི་སྐབས་སུ་ཉེ་བར་མཁོ་བའི་གསལ་བྱེད།
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: 823d.txt
      order: 63
    8e78:
      title: ༼ན༽དཔལ་ཀྱཻ་རྡོ་རྗེའི་སྒྲུབ་པའི་ཐབས་ཀྱི་རྒྱ་ཆེར་བཤད་པ་བསྐྱེད་རིམ་གནད་ཀྱི་ཟླ་ཟེར་ལ་རྩོད་པ་སྤོང་བ་གནད་ཀྱི་གསལ་བྱེད།
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: 8e78.txt
      order: 64
    4fb5:
      title: ༼པ༽སོག་པོ་བཀའ་བཅུ་པ། གོ་བོ་སངས་རྒྱས་རྒྱལ་མཚན། དྲུང་ཆེན་ཀུན་སྤངས་པ་རྣམས་ལ་གདམས་པ་རེ་རེ་བཞུགས།
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: 4fb5.txt
      order: 65
    bb3d:
      title: ༼པ༽ཀུན་མཁྱེན་བླ་མའི་གསུང་འབུམ་སྨོན་ལམ་གྱི་སྐོར་བཞུགས་སོ།།
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: bb3d.txt
      order: 66
    0fc3:
      title: ༼ཕ། ཁ་སྐོང་།༽ མུས་ཆེན་ཐུགས་རྗེ་དཔལ་བཟང་གིས་མཛད་པ། སྡེ་བདུན་མདོ་དང་བཅས་པའི་དགོངས་འགྲེལ་ཚད་མ་རིག་པའི་གཏེར་གྱི་འགྲེལ་པ་རིགས་ལམ་རབ་གསལ།
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: 0fc3.txt
      order: 67
    3eb0:
      title: ༼ཕ། ཁ་སྐོང་༽ ཀོང་སྟོན་དབང་ཕྱུག་གྲུབ་ཀྱིས་མཛད་པ། འདུལ་བ་མདོ་རྩ་བའི་སྤྱི་དོན་ལེགས་བཤད་འོད་ཀྱི་སྣང་བ་ཚིག་དོན་རབ་གསལ།
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: 3eb0.txt
      order: 68
    3fd3:
      title: ༼བ། ཁ་སྐོང་༽ མུས་ཆེན་ཐུགས་རྗེ་དཔལ་བཟང་གིས་མཛད་པ། དམ་པའི་ཆོས་མངོན་པ་མཛོད་ཀྱི་འགྲེལ་པ་གཞུང་དོན་རབ་ཏུ་གསལ་བའི་ཉི་མ།
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: 3fd3.txt
      order: 69
    68be:
      title: ༼བ། ཁ་སྐོང་༽ མུས་ཆེན་ཐུགས་རྗེ་དཔལ་བཟང་གིས་མཛད་པ། ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པའི་མན་ངག་གི་བསྟན་བཅོས་མངོན་པར་རྟོགས་པའི་རྒྱན་གྱི་འགྲེལ་པ་དགོངས་དོན་རབ་གསལ་ཞེས་བྱ་བ་བཞུགས་སོ།།
      author: ཀུན་མཁྱེན་གོ་རམས་པ་བསོད་ནམས་སེང་གེ།
      base_file: 68be.txt
      order: 70
created_at: '2022-04-06T17:35:56.378431'
last_modified_at: '2022-04-06T17:35:56.378503'
